baseurl = "https://example.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Hugo Theme Dream"
theme = "hugo-theme-dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Yue Yang"
  # description = ""
  avatar = "/img/avatar.jpg"
  motto = "Motto"
  
  email = "g1enyy0ung@gmail.com"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2016

  # favicon = "/favicon.ico"

  # options
  showSummaryCoverInPost = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404 = true
