baseurl = "https://example.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Hugo Theme Dream"
theme = "hugo-theme-dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

# recommended for GitHub pages
publishDir = 'docs'

[markup.goldmark.renderer] 
unsafe = true 

[params]
  background = "#f7f7f7"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  # dark mode
  # defaultDark = true
  # backgroundDark = "black"
  # backgroundImageDark = "/me/background-dark.jpg"
  # darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  author = "Yue Yang"
  # description = ""
  avatar = "/img/avatar.jpeg"
  # roundAvatar = true
  headerTitle = "Hugo Theme Dream"
  motto = "Motto"
  # maxTags = 5
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  # rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  # VALINE_LANGUAGE = ""

  # socials, deprecated - use /data/socials.toml instead
  email = "g1enyy0ung@gmail.com"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2016

  favicon = "/favicons/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsCDN = "js/3p/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  # enableSearch = true

  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # reversePostAndAside = true
  # shareInAside = true
  # fixedNav = true
  # collapsibleTags = true
  # collapseBySummary = true

  # [params.advanced]
  #   customCSS = ["css/custom.css"]
  #   customJSBefore = []
  #   customJS = []

  # [params.experimental]
  #   jsDate = true
  #   jsDateFormat = "yyyy年MM月dd日"
  
    [params.advanced]
    customCSS = ["css/custom.css"] # files in the list will be loaded in order
  
  # required for search
  # [outputs]
  #   home = ["HTML", "RSS", "JSON"]